name: 'Test'
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMG_TAG: express-app-img
  DOCKER_CONTAINER_NAME: express-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Get npm Cache Directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: Cache npm Dependencies
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        id: docker-build
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ env.DOCKER_IMG_TAG }} 
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: List Docker Image
        run: |
          docker image ls
      - name: Run Docker Container
        run: docker container run -d --rm --name $DOCKER_CONTAINER_NAME -p 3000:3000 $DOCKER_IMG_TAG
      - name: Test
        run: npm test 
