name: 'Test'
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Check Docker Image Cache
        id: docker-img-cache
        uses: actions/cache@v4
        with:
          path: /tmp/img.tar
          key: docker-img-cache
      - name: Load Docker Image Cache and Build
        if: steps.docker-img-cache.outputs.cache-hit == 'true'
        run: |
          echo ---- docker image ls before load ----
          docker image ls
          echo ---- docker image load from cache ----
          docker image load --input /tmp/img.tar
          echo ---- docker image retag ----
          docker image tag express-app-img express-app-img-cache
          docker image rm express-app-img
          echo ---- docker image ls after load ----
          docker image ls
          echo ---- docker image build from cache ----
          docker image build -t express-app-img --cache-from express-app-img-cache . 
      - name: Build Docker Image 
        if: steps.docker-img-cache.outputs.cache-hit != 'true'
        run: |
          echo ---- docker image build ----
          docker image build -t express-app-img . 
      - name: Save Docker image 
        run: |
          echo ---- docker image save ----
          docker image save --output /tmp/img.tar express-app-img
      - name: Run Docker Container
        run: docker container run -d --rm --name express-app -p 3000:3000 express-app-img
      - name: Test
        run: npm test 
